### ISSUE TITLE
ParameterMap can't handle string parameters

### ISSUE THREAD

**Issue by law909** [zoho/zohocrm-php-sdk-6.0#2]
When adding a string parameter like
```
$params->add(new \com\zoho\crm\api\Param('fields'), 'id,Last_Name,Email');
```
get_class($value) in line 70 throws an \Error on PHP 8, but code catches \Exception. Should catch \Throwable.

**Comment by raja-k-7453** [comment]
@law909 Please try the sample code provided below.

``$paramInstance->add(new \com\zoho\crm\api\Param('fields',"String"), 'id,Last_Name,Email');``

Please forward any SDK-related queries to [support@zohocrm.com](mailto:support@zohocrm.com) and we'll take things forward.
