### ISSUE TITLE
createTaxes is missing

### ISSUE THREAD

**Issue by meetanshitechnologies** [zoho/zohocrm-php-sdk-6.0#7]
Hello,
createTaxes() function is missing in com\zoho\crm\api\taxes\TaxesOperations class.
any reason behind removal?

**Comment by raja-k-7453** [comment]
Thanks, @meetanshigit for your contribution. Refer to the following sample code for creating/updating/deleting taxes.
https://github.com/zoho/zohocrm-php-sdk-6.0/blob/master/samples/taxes/UpdateTaxes.php
